# air_salagiochi
# air_salagiochi_out
# air_ingresso_out
# air_studio

esphome:
  name: air_salagiochi
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "JEDI"
  password: "Qelnp72!"

logger:
  level: DEBUG

api:

ota:
  safe_mode: True
  
web_server:
  port: 80

time:
  - platform: sntp
    timezone: Europe/Rome
    servers: time.google.com

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: True

uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: True

sensor:
  - platform: sds011
    pm_2_5:
      name: "SalaGiochi : Particolato pm 2.5"
    pm_10_0:
      name: "SalaGiochi : Particolato pm 10"
    update_interval: 30min
  - platform: sht3xd
    temperature:
      name: "SalaGiochi : Temperatura"
    humidity:
      name: "SalaGiochi : Umidità"
    address: 0x44
    update_interval: 60s

